name: godPowers
main: com.hydrasmp.godPowers.godPowers
version: ${project.version}
author: Hydra SMP
commands:
    bless:
        description: Enchants all items in inv.
        usage: /bless
    demigod:
        description: Reduces damage by an adjustable rate.
        usage: /demigod
    die:
        description: I wonder what this does! :o
        usage: /die
    dupe:
        description: Duplicates the item in your hand
        usage: /dupe <amount>
    fusrodah:
        description: Puts knockback lvl 10 on held item.
        usage: /fusrodah
    gaia:
        description: Beautify the earth with every step you take.
        usage: /gaia
    godmode:
        description: Become invincible!
        usage: /godMode
    godmodeon:
        description: Enable godmode (Temporary fix for conflict with Essentials).
        usage: /godmodeon
    godmodeoff:
        description: Disable godmode (Temporary fix for conflict with Essentials).
        usage: /godmodeoff
    godpowers:
        description: Displays avaliable commands.
        usage: /godpowers
    hades:
        description: Corrupts the world beneath your feet.
        usage: /hades
    heal:
        description: Heals you. Duh.
        usage: /heal
    hermes:
        description: Gives you the powers of heremes
        usage: /hermes
    inferno:
        description: Burn the ground behind you with the power of your fiery rage!
        usage: /inferno
    jesus:
        description: You feel like you can walk on water.... Maybe even lava!
        usage: /jesus
    maim:
        description: Beat those disobediant players within an inch of their lives!
        usage: /maim
    medusa:
        description: Curses you with he ability to turn people to stone
        usage: /medusa
    myballsareonfire:
        description: See vulcan.
        usage: /myballsareonfire
    plutus:
        description: Puts wealth lvl 10 on held item.
        usage: /plutus
    poseidon:
        description: Gives you poseidon like powers while in water
        usage: /poseidon
    slay:
        description: Slay your enemies with just the press of a few keys!
        usage: /slay
    superjump:
        description: Gain the ability to leap tall buildings in a single bound!
        usage: /superjump
    vulcan:
        description: Goodness gracious, great balls of fire!
        usage: /vulcan
    zeus:
        description: Strike lightning were you're looking.
        usage: /zeus
permissions:
    godpowers.*:
        description: Gives access to all godpowers commands.
        children:
            godpowers.bless: true
            godpowers.demigod: true
            godpowers.die: true
            godpowers.dupe: true
            godpowers.fusrodah: true
            godpowers.gaia: true
            godpowers.godmode: true
            godpowers.godmodeonlogin: true
            godpowers.godtools: true
            godpowers.hades: true
            godpowers.heal: true
            godpowers.hermes: true
            godpowers.inferno: true
            godpowers.jesus: true
            godpowers.maim: true
            godpowers.medusa: true
            godpowers.poseidon: true
            godpowers.slay: true
            godpowers.superjump: true
            godpowers.vulcan: true
            godpowers.zeus: true
    godpowers.bless:
        description: Gives permission to relevant command.
        default: op
    godpowers.demigod:
        description: Gives permission to relevant command.
        default: op
    godpowers.die:
        description: Gives permission to relevant command.
        default: op
    godpowers.dupe:
        description: Gives permission to relevant command.
        default: op
    godpowers.fusrodah:
        description: Gives permission to relevant command.
        default: op
    godpowers.gaia:
        description: Gives permission to relevant command.
        default: op
    godpowers.godmode:
        description: Gives permission to relevant command.
        default: op
    godpowers.godmodeonlogin:
        description: Allows godmode upon login.
        default: op
    godpowers.godtools:
        description: Gives permission to godtools.
        default: op
    godpowers.hades:
        description: Gives permission to relevant command.
        default: op
    godpowers.heal:
        description: Gives permission to relevant command.
        default: op
    godpowers.hermes:
        description: Gives permission to relevant command.
        default: op
    godpowers.inferno:
        description: Gives permission to relevant command.
        default: op
    godpowers.jesus:
        description: Gives permission to relevant command.
        default: op
    godpowers.maim:
        description: Gives permission to relevant command.
        default: op
    godpowers.medusa:
        description: Gives permission to relevant command.
        default: op
    godpowers.poseidon:
        description: Gives permission to relevant command.
        default: op
    godpowers.slay:
        description: Gives permission to relevant command.
        default: op
    godpowers.superjump:
        description: Gives permission to relevant command.
        default: op
    godpowers.vulcan:
        description: Gives permission to relevant command.
        default: op
    godpowers.zeus:
        description: Gives permission to relevant command.
        default: op

